# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  # title = "Engineering notes"
  copyright = "&copy; Vladimir Plizga {year}"
  [en.params]
    description = "Personal professional web page"
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "Jan 2, 2006"
    #   Examples: "3:04 pm" or "15:04"
    time_format = "3:04 PM"

# Configure the Russian version of the site.
[ru]
  languageCode = "ru-ru"
  contentDir = "content/ru"
  # title = "Инженерные заметки"
  copyright = "&copy; Владимир Плизг&aacute; {year}"
  [ru.params]
    description = "Личная профессиональная страница"
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "02.01.2006"
    #   Examples: "3:04 pm" or "15:04"
    time_format = "15:04"
